export const ADMIN_LOGIN = '+70000000000'

export const OTP_CODE_MOCK = '123456'

export const OTP_TTL_SECONDS = 300
export const OTP_TTL_MS = OTP_TTL_SECONDS * 1000

export const OTP_RESEND_MIN_INTERVAL_SECONDS = 30
export const OTP_RESEND_MIN_INTERVAL_MS = OTP_RESEND_MIN_INTERVAL_SECONDS * 1000

export const OTP_MAX_ATTEMPTS = 5

export const IDENTITY_LOCK_MINUTES = 15
export const IDENTITY_LOCK_MS = IDENTITY_LOCK_MINUTES * 60 * 1000

export const ACCESS_TOKEN_EXPIRES_IN_SECONDS = 60 * 60
